### ISSUE TITLE
可以支持pcm转mp3或者wav ？

### ISSUE THREAD

**Issue by wangjianpeng** [3wz/Lame-For-Unity#1]
我看到有 WaveFileReader ， 是不是修改后，就能用来把pcm 转为为 mp3或者wav ，可以在android上正常使用？

**Comment by mi1890** [comment]
我这里可以用,ios,android,pc,mac都可以用
pcm转wav,应该只是加个文件头就可以了

**Comment by 3wz** [comment]
PCM数据加上头就变成了wav文件, 然后再用代码转成MP3即可.
