### ISSUE TITLE
bulid的时候报错，提示无法找到dll文件

### ISSUE THREAD

**Issue by KirbyXcode** [3wz/Lame-For-Unity#5]
build to Win10 platform的时候发生的问题。
报错信息：Assets/Lame/LibMp3Lame.cs(714,24): error CS0103: The name `libname' does not exist in the current context

我不确定是不是Plugins目录下的dll文件使用的框架版本太高导致的问题。
一般来说应该是载入.net target 3.5，而plugins下的x86 x64的dll文件显然是高于unity限制的.net版本框架的。不知道楼主有没有同样的问题。

**Comment by 3wz** [comment]
在LibMp3Lame.cs脚本中680行我只判断了编辑器, osx, 安卓和ios, 其他平台没加宏判断, 应该是这边的报错, 你加上对应平台的宏判断, 然后给libname合适的一个名字即可
