### ISSUE TITLE
Add a license (suggestion: MIT license)

### ISSUE THREAD

**Issue by CanisLupus** [3wz/Lame-For-Unity#6]
Hey!

Could you please add a license to the repository?

Currently nobody can legally use your project or parts of it because not having a license means that only you (the author) has the rights to the code. It's possible that this is intended, but more often than not the author just forgot to add a license. :)

If you wish to add a license I suggest using the MIT license, but that is your choice.

Thanks!
Daniel

**Comment by 3wz** [comment]
MIT license has been added.
